### ISSUE TITLE
Regarding 'Running multiple servers'

### ISSUE THREAD

**Issue by Vel-San** [dwurf/docker-kf2#19]
Hey @dwurf !

I recently did a complete overhaul to my kf1-docker installation/image. It now supports several new env vars such as ports to enable support for Multiple servers.

I noticed, your current solution for this is using a docker-compose and increment the ports. My question is, does this actually work if you're running servers on the same machine just fine? is it OK to increment steam ports? 

My use case:

I ran my first server using a docker run just fine, it works and I can see it. This is using default ports (For both, Steam and the game itself).

Now I want to spin up a new container with new volume etc... for a 2nd server. I increment 3 ports (which can be changed within Killingfloor.ini), but the other 3 which are related to steam I cannot change. docker is complaing that my 1st server is still using these ports.. I'm not sure if your solution also fixes this?

My current docker-compose:

```yml
version: '2'

services:
    Server2:
        container_name: Nanu-Nanu-2-NUC
        image: vel7an/kf1-docker:latest
        restart: always
        ports:
            - 0.0.0.0:7709:7709/udp # Changed in Killingfloor.ini
            - 0.0.0.0:7719:7719/udp # Changed in Killingfloor.ini
            - 0.0.0.0:8077:8077/tcp # Changed in Killingfloor.ini
            - 0.0.0.0:7708:7708/udp # Cannot use because Server1 is using it
            - 0.0.0.0:28852:28852/udp # Cannot use because Server1 is using it
            - 0.0.0.0:28852:28852/tcp # Cannot use because Server1 is using it
            - 0.0.0.0:20560:20560/udp # Cannot use because Server1 is using it
            - 0.0.0.0:20560:20560/tcp # Cannot use because Server1 is using it
        environment:
            - KF_MAP=KF-BioticsLab
            - KF_DIFFICULTY=4
            - KF_GAME_LENGTH=2
            - KF_GAME_PASS=
            - KF_SERVER_NAME=Hosts of SeraphiM
            - KF_ADMIN_NAME=Vel
            - KF_ADMIN_PASS=XXX
            - KF_ADMIN_EMAIL=Vel-San@ProtonMail.com
            - KF_MOTD=XXX
            - KF_REDIRECT=XXX
            - KF_MUTATORS=MutLoader.MutLoader
            - STEAM_USER=user
            - STEAM_PASSWORD=secret
            - STEAM_CODE=12345
        volumes:
            - /home/vel/kf-stuff/server-volume-2:/home/steam/servers/kf
```

Server 1 running using the following:

>docker run -i --name Nanu-Nanu-NUC -p 0.0.0.0:7707:7707/udp -p 0.0.0.0:7708:7708/udp -p 0.0.0.0:7717:7717/udp -p 0.0.0.0:28852:28852/udp -p 0.0.0.0:28852:28852/tcp -p 0.0.0.0:8075:8075/tcp -p 0.0.0.0:20560:20560/udp -p 0.0.0.0:20560:20560/tcp -v /home/vel/kf-stuff/server-volume:/home/steam/servers/kf -e STEAM_USER=user -e STEAM_PASSWORD=secret -e STEAM_CODE=$1 --env-file=/home/vel/kf-stuff/env_file vel7an/kf1-docker

Do you have any ideas? Is it even possible to have 2 containers using same steam ports even with docker-compose? 

How does it work exactly with your setup? Are you also incrementing 20560?
